services:
  - type: web
    name: hipster-frontend
    env: node
    buildCommand: cd project && npm install && npm run build
    startCommand: cd project && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://rag-chatbot-nextjs.onrender.com
               
