services:
  - type: web
    name: hipster-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.backend_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: airport-index